{% set name = "opensearch-ws" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/opensearch/opensearch-ws/-/archive/0.9.0/opensearch-ws-{{ version }}.tar.gz
  sha256: 4b43da4e34c0f4c6e85048869acac8e10b632f811f63e30bfe885bd0670470fc

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - poetry
    - poetry-dynamic-versioning

  run:
    - python
    - naiad >=2.0.2
    - fastapi >=0.82,<1.0
    - fastapi-healthcheck >=0.2.7,<0.3
    - elasticsearch >=7.6,<8.0
    - python-dateutil >=2.8.1,<2.9
    - pytz >=2020.1,<2020.2
    - marshmallow >=3.6.1,<3.7
    - descartes >=1.1.0,<1.2
    - pyproj >=3.0.0,<4.0.0
    - certifi >=2020.4.5.2,<2020.4.6
    - jinja2 >=3.1.2,<3.2
    - uvicorn >=0.15.0
    - gunicorn >=20,<21
    - markupsafe >=2.0.1,<2.0.2

    
test:
  source_files:
    - tests
  imports:
    - opensearch-ws
  requires:
    - pytest >=6,<7
    - pytest-cov >=2,<3
    - coverage 
    - pytest-asyncio >=0.16.0
    - httpx >=0.21.1,<0.22
  commands:
    - pytest --pyargs tests

about:
  home: https://gitlab.ifremer.fr/opensearch/opensearch-ws
  license: Apache-2.0
  license_file: LICENSE
  summary: Web Service OpenSearch de découverte et d'accès aux données géospatiales hautes performances

extra:
  recipe-maintainers:
    - marie59
