{% set name = "jobard-client" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://gitlab.ifremer.fr/jobard/jobard_client.git
  git_tag: {{ version }}
  
build:
  script: 
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - poetry
    - poetry-dynamic-versioning

  run:
    - python
    - requests >=2.26.0,<2.30
    - pydantic >=1.8.2,<1.9
    - click >=8.0.2,<8.0.3
    - tabulate >=0.8.9,<0.9
    - pandas >=1.5,<2.0
    
test:
  imports:
    - jobard_client

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_client
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python client for Job Array Daemon.


extra:
  recipe-maintainers:
    - marie59
