{% set name = "felyx" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://gitlab.ifremer.fr/felyx/felyx_processor.git
  git_tag: {{ version }}

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - poetry
    - poetry-dynamic-versioning

  run:
    - python
    - dask >=2021.8.1,<2021.8.2
    - elasticsearch >=7.10.1,<7.11
    - numexpr >=2.7.1,<2.8
    - pyarrow >=9.0.0,<9.1
    - pydantic >=1.8.2,<1.9
    - pyyaml >=6.0.0,<7.0.0
    - requests >=2.26.0,<2.27
    - scipy >=1.5.3,<1.6
    - shapely >=1.7.1,<1.8
    - simplejson >=3.17.2,<3.18
    - pyinterp >=0.16.0,<0.17
    - polygon-geohasher >=0.0.1,<0.1
    - xarray >=2022.3.0,!=2022.6.0,<2022.10.0
    - packaging >=20.4,<21.0
    - cerbere
    
test:
  source_files:
    - tests
  imports:
    - felyx_processor
  requires:
    - pytest >=6,<7
    - pytest-cov >=2,<3
    - pytest-xdist >=2,<3
    - pytest-dependency >=0.5.1,<0.6
  commands:
    - pytest --pyargs tests

about:
  home: https://gitlab.ifremer.fr/felyx/felyx_processor
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: felyx is a free software solution, written in python, whose aim is to provide Earth Observation data producers and users with an open-source, flexible and reusable tool to allow scientific analysis and performance monitoring of scientific observation data through subsetting over specific areas or matching up with in situ measurements.

extra:
  recipe-maintainers:
    - marie59
