{% set name = "jobard-worker-dask" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_worker_dask/-/archive/{{ version }}/jobard_worker_dask-{{ version }}.tar.gz
  sha256: bb91450d1706270db374ace2f7f530f79e35397d3339ecef62a18b0c3d589bde

  
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - poetry
    - poetry-dynamic-versioning

  run:
    - python >=3.9
    - dask >=2021.10.0
    - distributed >=2021.10.0
    - cloudpickle >=2.0.0
    - click >=8.0.2
    
test:
  imports:
    - jobard_worker_dask

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_worker_dask
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Jobard dask worker initialization, used by jobard_remote_dask component.


extra:
  recipe-maintainers:
    - marie59
