{% set name = "jobard-daemon" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://gitlab.ifremer.fr/jobard/jobard_daemon.git
  git_tag: {{ version }}
  
build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - poetry
    - poetry-dynamic-versioning

  run:
    - python
    - pydantic >=1.8.2,<1.9
    - click >=8.0.2,<8.0.3
    - jinja2 >2
    - asyncssh >=2.9.0,<3.0.0
    - asyncpg >=0.25.0
    - pyyaml >=6.0,<7
    - pandas
    
test:
  source_files:
    - tests
  imports :
    - jobard_daemon
  requires:
    - pytest >=6,<7
    - pytest-cov >=2,<3
    - coverage 
  commands:
    - pytest --pyargs tests

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_daemon
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Job manager of the  Job Array Daemon.


extra:
  recipe-maintainers:
    - marie59
